const state={bootstrap:null,view:'client',customerId:'cliente-ana',actorId:'gestor-01',clientTicket:null,operatorTicket:null,queue:[],filter:'all'};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
async function api(path,options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||'Falha na operação');return data}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function escapeHtml(value){const div=document.createElement('div');div.textContent=value??'';return div.innerHTML}
function fmtTime(value){return new Date(value).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function badge(ticket){if(ticket.priority==='P0')return 'danger';if(ticket.status==='waiting_human')return 'warning';if(ticket.status==='resolved'||ticket.status==='awaiting_confirmation')return 'success';return 'neutral'}
async function init(){state.bootstrap=await api('/api/bootstrap');fillProfiles();$('#systemStatus').textContent=state.bootstrap.config.ai_configured?'API de IA conectada':'Modo local · configure a API';bind();await loadClientTickets();await loadQueue();if(new URLSearchParams(location.search).get('view')==='operator')switchView('operator')}
function fillProfiles(){const {customers,actors}=state.bootstrap.access;$('#customerSelect').innerHTML=customers.map(x=>`<option value="${x.id}">${escapeHtml(x.name)} · ${x.code}</option>`).join('');$('#actorSelect').innerHTML=actors.map(x=>`<option value="${x.id}">${escapeHtml(x.name)} · ${escapeHtml(x.label)}</option>`).join('');renderAccess()}
function bind(){
  $$('.view-tab').forEach(btn=>btn.onclick=()=>switchView(btn.dataset.view));
  $('#customerSelect').onchange=async e=>{state.customerId=e.target.value;state.clientTicket=null;$('#clientFirstName').textContent=e.target.selectedOptions[0].text.split(' ')[0];await loadClientTickets()};
  $('#actorSelect').onchange=async e=>{state.actorId=e.target.value;state.operatorTicket=null;renderAccess();await loadQueue()};
  $('#newConversation').onclick=()=>{state.clientTicket=null;renderClient(null);$('#clientInput').focus()};
  $$('.scenario-list button').forEach(btn=>btn.onclick=()=>{$('#clientInput').value=btn.dataset.scenario;$('#clientInput').focus()});
  $('#clientComposer').onsubmit=sendClient;$('#operatorComposer').onsubmit=sendOperator;
  $$('.filter').forEach(btn=>btn.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;renderQueue()});
  $('#statusSelect').onchange=changeStatus;
}
function switchView(view){state.view=view;$$('.view-tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#clientView').classList.toggle('active',view==='client');$('#operatorView').classList.toggle('active',view==='operator');if(view==='operator')loadQueue()}
function renderAccess(){const actor=state.bootstrap.access.actors.find(x=>x.id===state.actorId);$('#actorAccess').innerHTML=`<b>${escapeHtml(actor.label)}</b>Equipes: ${escapeHtml(actor.teams.join(', '))}<br>Permissões simuladas no servidor.`}
async function loadClientTickets(){const list=await api(`/api/client/conversations?customer_id=${encodeURIComponent(state.customerId)}`);const selected=state.clientTicket?list.find(x=>x.id===state.clientTicket.id):list[0];state.clientTicket=selected?await api(`/api/client/conversations/${selected.id}?customer_id=${encodeURIComponent(state.customerId)}`):null;renderClient(state.clientTicket)}
function renderMessages(el,ticket){if(!ticket){return}el.classList.remove('empty-state');el.innerHTML=ticket.messages.map(m=>`<div class="message ${m.author_type}"><div class="bubble">${escapeHtml(m.text)}<small>${escapeHtml(m.author_name)} · ${fmtTime(m.created_at)}</small></div></div>`).join('');el.scrollTop=el.scrollHeight}
function renderClient(ticket){if(!ticket){$('#clientTicketTitle').textContent='Novo atendimento';$('#clientTicketMeta').textContent='Envie uma mensagem para iniciar um chamado.';$('#clientRouteBadge').className='badge neutral';$('#clientRouteBadge').textContent='Pronto';$('#clientMessages').className='messages empty-state';$('#clientMessages').innerHTML='<div class="empty-icon">✦</div><h3>Como podemos ajudar?</h3><p>O assistente atende somente assuntos da Vértice e encaminha exceções com contexto.</p>';return}$('#clientTicketTitle').textContent=`${ticket.id} · ${ticket.subject}`;$('#clientTicketMeta').textContent=`${ticket.channel} · ${ticket.team}`;$('#clientRouteBadge').className=`badge ${badge(ticket)}`;$('#clientRouteBadge').textContent=ticket.status.replaceAll('_',' ');renderMessages($('#clientMessages'),ticket)}
async function sendClient(e){e.preventDefault();const input=$('#clientInput');const text=input.value.trim();if(!text)return;input.value='';try{if(!state.clientTicket){state.clientTicket=await api('/api/client/conversations',{method:'POST',body:JSON.stringify({customer_id:state.customerId,channel:$('#channelSelect').value,text})})}else{state.clientTicket=await api(`/api/client/conversations/${state.clientTicket.id}/messages`,{method:'POST',body:JSON.stringify({customer_id:state.customerId,text})})}renderClient(state.clientTicket);await loadQueue()}catch(err){toast(err.message)}}
async function loadQueue(){try{state.queue=await api(`/api/operator/conversations?actor_id=${encodeURIComponent(state.actorId)}`);$('#queueCount').textContent=state.queue.length;renderQueue();if(state.operatorTicket&&!state.queue.some(x=>x.id===state.operatorTicket.id)){state.operatorTicket=null;renderOperator(null)}}catch(err){toast(err.message)}}
function renderQueue(){const list=state.queue.filter(x=>state.filter==='all'||x.status===state.filter||x.priority===state.filter);$('#conversationList').innerHTML=list.map(x=>`<div class="conversation-card ${state.operatorTicket?.id===x.id?'active':''}" data-id="${x.id}"><div class="line"><strong>${escapeHtml(x.subject)}</strong><span class="priority ${x.priority.toLowerCase()}">${x.priority} · ${Number(x.score).toFixed(0)}</span></div><p>${escapeHtml(x.id)} · ${escapeHtml(x.channel)}</p><small>${escapeHtml(x.team)} · ${escapeHtml(x.status.replaceAll('_',' '))}</small></div>`).join('')||'<p class="muted">Nenhum chamado disponível para este perfil.</p>';$$('.conversation-card').forEach(card=>card.onclick=()=>openTicket(card.dataset.id))}
async function openTicket(id){try{state.operatorTicket=await api(`/api/operator/conversations/${id}?actor_id=${encodeURIComponent(state.actorId)}`);renderQueue();renderOperator(state.operatorTicket)}catch(err){toast(err.message)}}
function renderOperator(ticket){$('#operatorEmpty').classList.toggle('hidden',!!ticket);$('#operatorConversation').classList.toggle('hidden',!ticket);if(!ticket){$('#ticketContext').className='context-empty';$('#ticketContext').textContent='Selecione uma conversa para consultar rota, prioridade e eventos.';return}$('#operatorChannel').textContent=ticket.channel.toUpperCase();$('#operatorTicketTitle').textContent=`${ticket.id} · ${ticket.subject}`;$('#operatorTicketMeta').textContent=`${ticket.team} · rota ${ticket.route}`;$('#operatorPriority').className=`badge ${badge(ticket)}`;$('#operatorPriority').textContent=`${ticket.priority} · ${Number(ticket.score).toFixed(1)}`;$('#statusSelect').value=['waiting_human','in_progress','resolved'].includes(ticket.status)?ticket.status:'waiting_human';renderMessages($('#operatorMessages'),ticket);renderContext(ticket)}
function renderContext(t){$('#ticketContext').className='';$('#ticketContext').innerHTML=`<div class="context-block"><h3>Classificação</h3><div class="context-grid"><div class="context-value"><b>Categoria</b><span>${escapeHtml(t.category)}</span></div><div class="context-value"><b>Rota</b><span>${escapeHtml(t.route)}</span></div><div class="context-value"><b>Equipe</b><span>${escapeHtml(t.team)}</span></div><div class="context-value"><b>Responsável</b><span>${escapeHtml(t.assigned_to||'Não atribuído')}</span></div></div></div><div class="context-block"><h3>Eventos</h3>${t.events.slice().reverse().map(e=>`<div class="event"><b>${escapeHtml(e.type)}</b><br>${escapeHtml(e.detail)} · ${fmtTime(e.created_at)}</div>`).join('')}</div>`}
async function sendOperator(e){e.preventDefault();const text=$('#operatorInput').value.trim();if(!text||!state.operatorTicket)return;$('#operatorInput').value='';try{state.operatorTicket=await api(`/api/operator/conversations/${state.operatorTicket.id}/messages`,{method:'POST',body:JSON.stringify({actor_id:state.actorId,text})});renderOperator(state.operatorTicket);await loadQueue()}catch(err){toast(err.message)}}
async function changeStatus(){if(!state.operatorTicket)return;try{state.operatorTicket=await api(`/api/operator/conversations/${state.operatorTicket.id}/status`,{method:'POST',body:JSON.stringify({actor_id:state.actorId,status:$('#statusSelect').value})});renderOperator(state.operatorTicket);await loadQueue()}catch(err){toast(err.message)}}
init().catch(err=>toast(err.message));
